name: noto
permissions:
  contents: write
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 1 */3 * 

jobs:
  noto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: the
        run: cargo run --bin noto --release
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: notoize
