name: the
permissions:
  contents: write
on:
  workflow_dispatch:
  repository_dispatch:
    types: [run-scheduled-trigger]

jobs:
  the:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: the
        run: cargo run --bin data --release
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: update
          
